FROM golang:1

ENV PROJECT=concepts-rw-neo4j

ENV ORG_PATH="github.com/Financial-Times"
ENV SRC_FOLDER="${GOPATH}/src/${ORG_PATH}/${PROJECT}"

ARG GITHUB_USERNAME
ARG GITHUB_TOKEN

WORKDIR ${SRC_FOLDER}

RUN echo "Fetching dependencies..." \
  && git clone https://github.com/vishnubob/wait-for-it.git \
  && cd wait-for-it \
  && mv ./wait-for-it.sh ${SRC_FOLDER} \
  && git config --global url."https://${GITHUB_USERNAME}:${GITHUB_TOKEN}@github.com".insteadOf "https://github.com"

COPY go.mod /
COPY go.sum /
RUN go mod download

COPY . ${SRC_FOLDER}

ENTRYPOINT ["./wait-for-it.sh", "neo4j:7474", "-t", "60", "--"]
