version: '3'
services:
  test-runner:
    build:
      context: .
      dockerfile: Dockerfile.tests
    container_name: test-runner
    environment:
      - NEO4J_TEST_URL=http://neo4j:7474/db/neo4j
    command: ["go", "test", "-mod=readonly", "-race", "-tags=integration", "./..."]
    depends_on:
      - neo4j
  neo4j:
    image: neo4j:4.3-enterprise
    environment:
          NEO4J_AUTH: none
          NEO4J_ACCEPT_LICENSE_AGREEMENT: "yes"
    ports:
      - "7474:7474"
      - "7687:7687"
