version: 2
jobs:
  build:
    working_directory: /go/src/github.com/Financial-Times/concepts-rw-neo4j
    docker:
      - image: circleci/golang:1.10
        environment:
          CIRCLE_TEST_REPORTS: /tmp/test-reports
          CIRCLE_ARTIFACTS: /tmp/artifacts
      - image: neo4j:3.2.2-enterprise
        environment:
          NEO4J_AUTH: none
          NEO4J_HEAP_MEMORY: 256
          NEO4J_CACHE_MEMORY: 256M
    steps:
      - checkout
      - run:
          name: Create folders
          command: |
            mkdir -p $CIRCLE_TEST_REPORTS/golang
            mkdir -p $CIRCLE_ARTIFACTS
      - run:
          name: Download dependancies
          command: |
            go get -u github.com/golang/dep/cmd/dep
            go get -u github.com/jstemmer/go-junit-report
            go get -u github.com/mattn/goveralls
      - run:
          name: Download vendored dependancies
          command: |
            dep ensure
      - run:
          name: Build app
          command: |
            go build -v
      - run:
          name: Run tests and create coverage report
          command: |
            go test ./... -v -race -cover -coverprofile=$CIRCLE_ARTIFACTS/coverage.out | go-junit-report > $CIRCLE_TEST_REPORTS/golang/junit.xml
            sed -i "/_mock/d" ${CIRCLE_ARTIFACTS}/coverage.out
      - run:
          name: Upload coverage report
          command: |
            goveralls -coverprofile=$CIRCLE_ARTIFACTS/coverage.out -service=circle-ci -repotoken=$COVERALLS_TOKEN
      - store_test_results:
          path: /tmp/test-reports
      - store_artifacts:
          path: /tmp/artifacts
          destination: build
  docker_build:
    working_directory: /concepts-rw-neo4j
    docker:
      - image: docker:18.03
    steps:
      - checkout
      - setup_docker_engine
      - run:
          name: Build Dockerfile
          command: docker build .
workflows:
  version: 2
  tests_and_docker:
    jobs:
      - build
      - docker_build:
          requires:
            - build