fields:
  strapline:
    neoProp: "strapline"
    type: "string"
  descriptionXML:
    neoProp: "descriptionXML"
    type: "string"
  _imageUrl:
    neoProp: "imageUrl"
    type: "string"
  emailAddress:
    neoProp: "emailAddress"
    type: "string"
  facebookPage:
    neoProp: "facebookPage"
    type: "string"
  twitterHandle:
    neoProp: "twitterHandle"
    type: "string"
  scopeNote:
    neoProp: "scopeNote"
    type: "string"
  shortLabel:
    neoProp: "shortLabel"
    type: "string"
  properName:
    neoProp: "properName"
    type: "string"
  shortName:
    neoProp: "shortName"
    type: "string"
  countryCode:
    neoProp: "countryCode"
    type: "string"
  countryOfRisk:
    neoProp: "countryOfRisk"
    type: "string"
  countryOfIncorporation:
    neoProp: "countryOfIncorporation"
    type: "string"
  countryOfOperations:
    neoProp: "countryOfOperations"
    type: "string"
  postalCode:
    neoProp: "postalCode"
    type: "string"
  leiCode:
    neoProp: "leiCode"
    type: "string"
  iso31661:
    neoProp: "iso31661"
    type: "string"
  salutation:
    neoProp: "salutation"
    type: "string"
  industryIdentifier:
    neoProp: "industryIdentifier"
    type: "string"
  aliases:
    neoProp: "aliases"
    type: "[]string"
  formerNames:
    neoProp: "formerNames"
    type: "[]string"
  tradeNames:
    neoProp: "tradeNames"
    type: "[]string"
  yearFounded:
    neoProp: "yearFounded"
    type: "int"
  birthYear:
    neoProp: "birthYear"
    type: "int"
relationships:
  HAS_PARENT:
    conceptField: "parentUUIDs"
    neoCreate: true
  HAS_BROADER:
    conceptField: "broaderUUIDs"
  IS_RELATED_TO:
    conceptField: "relatedUUIDs"
  SUPERSEDED_BY:
    conceptField: "supersededByUUIDs"
  IMPLIED_BY:
    conceptField: "impliedByUUIDs"
  HAS_FOCUS:
    conceptField: "hasFocusUUIDs"
  HAS_ORGANISATION:
    conceptField: "organisationUUID"
    oneToOne: true
    neoCreate: true
  HAS_MEMBER:
    conceptField: "personUUID"
    oneToOne: true
    neoCreate: true
  COUNTRY_OF_RISK:
    conceptField: "countryOfRiskUUID"
    oneToOne: true
    neoCreate: true
  COUNTRY_OF_INCORPORATION:
    conceptField: "countryOfIncorporationUUID"
    oneToOne: true
    neoCreate: true
  COUNTRY_OF_OPERATIONS:
    conceptField: "countryOfOperationsUUID"
    oneToOne: true
    neoCreate: true
  SUB_ORGANISATION_OF:
    conceptField: "parentOrganisation"
    oneToOne: true
    neoCreate: true
authorities:
  - TME
  - FACTSET
  - UPP
  - LEI
  - Smartlogic
  - ManagedLocation
  - ISO-3166-1
  - Geonames
  - Wikidata
  - DBPedia
  - NAICS
