package ontology

func TransformToNewSourceConcept(c SourceConcept) NewSourceConcept {
	concept := NewSourceConcept{
		GenericConcept:               GenericConcept{},
		UUID:                         c.UUID,
		PrefLabel:                    c.PrefLabel,
		Type:                         c.Type,
		Authority:                    c.Authority,
		AuthorityValue:               c.AuthorityValue,
		LastModifiedEpoch:            c.LastModifiedEpoch,
		Aliases:                      c.Aliases,
		ParentUUIDs:                  c.ParentUUIDs,
		Strapline:                    c.Strapline,
		DescriptionXML:               c.DescriptionXML,
		ImageURL:                     c.ImageURL,
		EmailAddress:                 c.EmailAddress,
		FacebookPage:                 c.FacebookPage,
		TwitterHandle:                c.TwitterHandle,
		ScopeNote:                    c.ScopeNote,
		ShortLabel:                   c.ShortLabel,
		BroaderUUIDs:                 c.BroaderUUIDs,
		RelatedUUIDs:                 c.RelatedUUIDs,
		SupersededByUUIDs:            c.SupersededByUUIDs,
		ImpliedByUUIDs:               c.ImpliedByUUIDs,
		HasFocusUUIDs:                c.HasFocusUUIDs,
		OrganisationUUID:             c.OrganisationUUID,
		PersonUUID:                   c.PersonUUID,
		Hash:                         c.Hash,
		MembershipRoles:              c.MembershipRoles,
		InceptionDate:                c.InceptionDate,
		TerminationDate:              c.TerminationDate,
		InceptionDateEpoch:           c.InceptionDateEpoch,
		TerminationDateEpoch:         c.TerminationDateEpoch,
		FigiCode:                     c.FigiCode,
		IssuedBy:                     c.IssuedBy,
		ProperName:                   c.ProperName,
		ShortName:                    c.ShortName,
		TradeNames:                   c.TradeNames,
		FormerNames:                  c.FormerNames,
		CountryCode:                  c.CountryCode,
		CountryOfRisk:                c.CountryOfRisk,
		CountryOfIncorporation:       c.CountryOfIncorporation,
		CountryOfOperations:          c.CountryOfOperations,
		CountryOfRiskUUID:            c.CountryOfRiskUUID,
		CountryOfIncorporationUUID:   c.CountryOfIncorporationUUID,
		CountryOfOperationsUUID:      c.CountryOfOperationsUUID,
		PostalCode:                   c.PostalCode,
		YearFounded:                  c.YearFounded,
		LeiCode:                      c.LeiCode,
		ParentOrganisation:           c.ParentOrganisation,
		NAICSIndustryClassifications: c.NAICSIndustryClassifications,
		IsDeprecated:                 c.IsDeprecated,
		ISO31661:                     c.ISO31661,
		Salutation:                   c.Salutation,
		BirthYear:                    c.BirthYear,
		IndustryIdentifier:           c.IndustryIdentifier,
	}
	return concept
}

func TransformToOldSourceConcept(c NewSourceConcept) SourceConcept {
	concept := SourceConcept{
		UUID:                         c.UUID,
		PrefLabel:                    c.PrefLabel,
		Type:                         c.Type,
		Authority:                    c.Authority,
		AuthorityValue:               c.AuthorityValue,
		LastModifiedEpoch:            c.LastModifiedEpoch,
		Aliases:                      c.Aliases,
		ParentUUIDs:                  c.ParentUUIDs,
		Strapline:                    c.Strapline,
		DescriptionXML:               c.DescriptionXML,
		ImageURL:                     c.ImageURL,
		EmailAddress:                 c.EmailAddress,
		FacebookPage:                 c.FacebookPage,
		TwitterHandle:                c.TwitterHandle,
		ScopeNote:                    c.ScopeNote,
		ShortLabel:                   c.ShortLabel,
		BroaderUUIDs:                 c.BroaderUUIDs,
		RelatedUUIDs:                 c.RelatedUUIDs,
		SupersededByUUIDs:            c.SupersededByUUIDs,
		ImpliedByUUIDs:               c.ImpliedByUUIDs,
		HasFocusUUIDs:                c.HasFocusUUIDs,
		OrganisationUUID:             c.OrganisationUUID,
		PersonUUID:                   c.PersonUUID,
		Hash:                         c.Hash,
		MembershipRoles:              c.MembershipRoles,
		InceptionDate:                c.InceptionDate,
		TerminationDate:              c.TerminationDate,
		InceptionDateEpoch:           c.InceptionDateEpoch,
		TerminationDateEpoch:         c.TerminationDateEpoch,
		FigiCode:                     c.FigiCode,
		IssuedBy:                     c.IssuedBy,
		ProperName:                   c.ProperName,
		ShortName:                    c.ShortName,
		TradeNames:                   c.TradeNames,
		FormerNames:                  c.FormerNames,
		CountryCode:                  c.CountryCode,
		CountryOfRisk:                c.CountryOfRisk,
		CountryOfIncorporation:       c.CountryOfIncorporation,
		CountryOfOperations:          c.CountryOfOperations,
		CountryOfRiskUUID:            c.CountryOfRiskUUID,
		CountryOfIncorporationUUID:   c.CountryOfIncorporationUUID,
		CountryOfOperationsUUID:      c.CountryOfOperationsUUID,
		PostalCode:                   c.PostalCode,
		YearFounded:                  c.YearFounded,
		LeiCode:                      c.LeiCode,
		ParentOrganisation:           c.ParentOrganisation,
		NAICSIndustryClassifications: c.NAICSIndustryClassifications,
		IsDeprecated:                 c.IsDeprecated,
		ISO31661:                     c.ISO31661,
		Salutation:                   c.Salutation,
		BirthYear:                    c.BirthYear,
		IndustryIdentifier:           c.IndustryIdentifier,
	}
	return concept
}

func TransformToNewAggregateConcept(c AggregatedConcept) NewAggregatedConcept {
	var sources []NewSourceConcept
	for _, s := range c.SourceRepresentations {
		sources = append(sources, TransformToNewSourceConcept(s))
	}
	concept := NewAggregatedConcept{
		GenericConcept:         GenericConcept{},
		PrefUUID:               c.PrefUUID,
		PrefLabel:              c.PrefLabel,
		Type:                   c.Type,
		Aliases:                c.Aliases,
		Strapline:              c.Strapline,
		DescriptionXML:         c.DescriptionXML,
		ImageURL:               c.ImageURL,
		EmailAddress:           c.EmailAddress,
		FacebookPage:           c.FacebookPage,
		TwitterHandle:          c.TwitterHandle,
		ScopeNote:              c.ScopeNote,
		ShortLabel:             c.ShortLabel,
		OrganisationUUID:       c.OrganisationUUID,
		PersonUUID:             c.PersonUUID,
		AggregatedHash:         c.AggregatedHash,
		SourceRepresentations:  sources,
		MembershipRoles:        c.MembershipRoles,
		InceptionDate:          c.InceptionDate,
		TerminationDate:        c.TerminationDate,
		InceptionDateEpoch:     c.InceptionDateEpoch,
		TerminationDateEpoch:   c.TerminationDateEpoch,
		FigiCode:               c.FigiCode,
		IssuedBy:               c.IssuedBy,
		ProperName:             c.ProperName,
		ShortName:              c.ShortName,
		TradeNames:             c.TradeNames,
		FormerNames:            c.FormerNames,
		CountryCode:            c.CountryCode,
		CountryOfRisk:          c.CountryOfRisk,
		CountryOfIncorporation: c.CountryOfIncorporation,
		CountryOfOperations:    c.CountryOfOperations,
		PostalCode:             c.PostalCode,
		YearFounded:            c.YearFounded,
		LeiCode:                c.LeiCode,
		IsDeprecated:           c.IsDeprecated,
		ISO31661:               c.ISO31661,
		Salutation:             c.Salutation,
		BirthYear:              c.BirthYear,
		IndustryIdentifier:     c.IndustryIdentifier,
	}
	return concept
}

func TransformToOldAggregateConcept(c NewAggregatedConcept) AggregatedConcept {
	var sources []SourceConcept
	for _, s := range c.SourceRepresentations {
		sources = append(sources, TransformToOldSourceConcept(s))
	}
	concept := AggregatedConcept{
		PrefUUID:               c.PrefUUID,
		PrefLabel:              c.PrefLabel,
		Type:                   c.Type,
		Aliases:                c.Aliases,
		Strapline:              c.Strapline,
		DescriptionXML:         c.DescriptionXML,
		ImageURL:               c.ImageURL,
		EmailAddress:           c.EmailAddress,
		FacebookPage:           c.FacebookPage,
		TwitterHandle:          c.TwitterHandle,
		ScopeNote:              c.ScopeNote,
		ShortLabel:             c.ShortLabel,
		OrganisationUUID:       c.OrganisationUUID,
		PersonUUID:             c.PersonUUID,
		AggregatedHash:         c.AggregatedHash,
		SourceRepresentations:  sources,
		MembershipRoles:        c.MembershipRoles,
		InceptionDate:          c.InceptionDate,
		TerminationDate:        c.TerminationDate,
		InceptionDateEpoch:     c.InceptionDateEpoch,
		TerminationDateEpoch:   c.TerminationDateEpoch,
		FigiCode:               c.FigiCode,
		IssuedBy:               c.IssuedBy,
		ProperName:             c.ProperName,
		ShortName:              c.ShortName,
		TradeNames:             c.TradeNames,
		FormerNames:            c.FormerNames,
		CountryCode:            c.CountryCode,
		CountryOfRisk:          c.CountryOfRisk,
		CountryOfIncorporation: c.CountryOfIncorporation,
		CountryOfOperations:    c.CountryOfOperations,
		PostalCode:             c.PostalCode,
		YearFounded:            c.YearFounded,
		LeiCode:                c.LeiCode,
		IsDeprecated:           c.IsDeprecated,
		ISO31661:               c.ISO31661,
		Salutation:             c.Salutation,
		BirthYear:              c.BirthYear,
		IndustryIdentifier:     c.IndustryIdentifier,
	}
	return concept
}
