package ontology

func TransformToNewAggregateConcept(old AggregatedConcept) NewAggregatedConcept {
	var newSources []NewConcept
	for _, s := range old.SourceRepresentations {
		newSources = append(newSources, TransformToNewSourceConcept(s))
	}

	return NewAggregatedConcept{
		PrefUUID:               old.PrefUUID,
		PrefLabel:              old.PrefLabel,
		Type:                   old.Type,
		Aliases:                old.Aliases,
		Strapline:              old.Strapline,
		DescriptionXML:         old.DescriptionXML,
		ImageURL:               old.ImageURL,
		EmailAddress:           old.EmailAddress,
		FacebookPage:           old.FacebookPage,
		TwitterHandle:          old.TwitterHandle,
		ScopeNote:              old.ScopeNote,
		ShortLabel:             old.ShortLabel,
		OrganisationUUID:       old.OrganisationUUID,
		PersonUUID:             old.PersonUUID,
		AggregatedHash:         old.AggregatedHash,
		MembershipRoles:        old.MembershipRoles,
		InceptionDate:          old.InceptionDate,
		TerminationDate:        old.TerminationDate,
		InceptionDateEpoch:     old.InceptionDateEpoch,
		TerminationDateEpoch:   old.TerminationDateEpoch,
		FigiCode:               old.FigiCode,
		IssuedBy:               old.IssuedBy,
		ProperName:             old.ProperName,
		ShortName:              old.ShortName,
		TradeNames:             old.TradeNames,
		FormerNames:            old.FormerNames,
		CountryCode:            old.CountryCode,
		CountryOfRisk:          old.CountryOfRisk,
		CountryOfIncorporation: old.CountryOfIncorporation,
		CountryOfOperations:    old.CountryOfOperations,
		PostalCode:             old.PostalCode,
		YearFounded:            old.YearFounded,
		LeiCode:                old.LeiCode,
		IsDeprecated:           old.IsDeprecated,
		ISO31661:               old.ISO31661,
		Salutation:             old.Salutation,
		BirthYear:              old.BirthYear,
		IndustryIdentifier:     old.IndustryIdentifier,
		SourceRepresentations:  newSources,
	}
}

func TransformToOldAggregateConcept(new NewAggregatedConcept) AggregatedConcept {
	var oldSources []Concept
	for _, s := range new.SourceRepresentations {
		oldSources = append(oldSources, TransformToOldSourceConcept(s))
	}

	return AggregatedConcept{
		PrefUUID:               new.PrefUUID,
		PrefLabel:              new.PrefLabel,
		Type:                   new.Type,
		Aliases:                new.Aliases,
		Strapline:              new.Strapline,
		DescriptionXML:         new.DescriptionXML,
		ImageURL:               new.ImageURL,
		EmailAddress:           new.EmailAddress,
		FacebookPage:           new.FacebookPage,
		TwitterHandle:          new.TwitterHandle,
		ScopeNote:              new.ScopeNote,
		ShortLabel:             new.ShortLabel,
		OrganisationUUID:       new.OrganisationUUID,
		PersonUUID:             new.PersonUUID,
		AggregatedHash:         new.AggregatedHash,
		MembershipRoles:        new.MembershipRoles,
		InceptionDate:          new.InceptionDate,
		TerminationDate:        new.TerminationDate,
		InceptionDateEpoch:     new.InceptionDateEpoch,
		TerminationDateEpoch:   new.TerminationDateEpoch,
		FigiCode:               new.FigiCode,
		IssuedBy:               new.IssuedBy,
		ProperName:             new.ProperName,
		ShortName:              new.ShortName,
		TradeNames:             new.TradeNames,
		FormerNames:            new.FormerNames,
		CountryCode:            new.CountryCode,
		CountryOfRisk:          new.CountryOfRisk,
		CountryOfIncorporation: new.CountryOfIncorporation,
		CountryOfOperations:    new.CountryOfOperations,
		PostalCode:             new.PostalCode,
		YearFounded:            new.YearFounded,
		LeiCode:                new.LeiCode,
		IsDeprecated:           new.IsDeprecated,
		ISO31661:               new.ISO31661,
		Salutation:             new.Salutation,
		BirthYear:              new.BirthYear,
		IndustryIdentifier:     new.IndustryIdentifier,
		SourceRepresentations:  oldSources,
	}
}

func TransformToNewSourceConcept(old Concept) NewConcept {
	return NewConcept{
		UUID:                         old.UUID,
		PrefLabel:                    old.PrefLabel,
		Type:                         old.Type,
		Authority:                    old.Authority,
		AuthorityValue:               old.AuthorityValue,
		LastModifiedEpoch:            old.LastModifiedEpoch,
		Aliases:                      old.Aliases,
		ParentUUIDs:                  old.ParentUUIDs,
		Strapline:                    old.Strapline,
		DescriptionXML:               old.DescriptionXML,
		ImageURL:                     old.ImageURL,
		EmailAddress:                 old.EmailAddress,
		FacebookPage:                 old.FacebookPage,
		TwitterHandle:                old.TwitterHandle,
		ScopeNote:                    old.ScopeNote,
		ShortLabel:                   old.ShortLabel,
		BroaderUUIDs:                 old.BroaderUUIDs,
		RelatedUUIDs:                 old.RelatedUUIDs,
		SupersededByUUIDs:            old.SupersededByUUIDs,
		ImpliedByUUIDs:               old.ImpliedByUUIDs,
		HasFocusUUIDs:                old.HasFocusUUIDs,
		OrganisationUUID:             old.OrganisationUUID,
		PersonUUID:                   old.PersonUUID,
		Hash:                         old.Hash,
		MembershipRoles:              old.MembershipRoles,
		InceptionDate:                old.InceptionDate,
		TerminationDate:              old.TerminationDate,
		InceptionDateEpoch:           old.InceptionDateEpoch,
		TerminationDateEpoch:         old.TerminationDateEpoch,
		FigiCode:                     old.FigiCode,
		IssuedBy:                     old.IssuedBy,
		ProperName:                   old.ProperName,
		ShortName:                    old.ShortName,
		TradeNames:                   old.TradeNames,
		FormerNames:                  old.FormerNames,
		CountryCode:                  old.CountryCode,
		CountryOfRisk:                old.CountryOfRisk,
		CountryOfIncorporation:       old.CountryOfIncorporation,
		CountryOfOperations:          old.CountryOfOperations,
		CountryOfRiskUUID:            old.CountryOfRiskUUID,
		CountryOfIncorporationUUID:   old.CountryOfIncorporationUUID,
		CountryOfOperationsUUID:      old.CountryOfOperationsUUID,
		PostalCode:                   old.PostalCode,
		YearFounded:                  old.YearFounded,
		LeiCode:                      old.LeiCode,
		ParentOrganisation:           old.ParentOrganisation,
		NAICSIndustryClassifications: old.NAICSIndustryClassifications,
		IsDeprecated:                 old.IsDeprecated,
		ISO31661:                     old.ISO31661,
		Salutation:                   old.Salutation,
		BirthYear:                    old.BirthYear,
		IndustryIdentifier:           old.IndustryIdentifier,
	}
}

func TransformToOldSourceConcept(new NewConcept) Concept {
	return Concept{
		UUID:                         new.UUID,
		PrefLabel:                    new.PrefLabel,
		Type:                         new.Type,
		Authority:                    new.Authority,
		AuthorityValue:               new.AuthorityValue,
		LastModifiedEpoch:            new.LastModifiedEpoch,
		Aliases:                      new.Aliases,
		ParentUUIDs:                  new.ParentUUIDs,
		Strapline:                    new.Strapline,
		DescriptionXML:               new.DescriptionXML,
		ImageURL:                     new.ImageURL,
		EmailAddress:                 new.EmailAddress,
		FacebookPage:                 new.FacebookPage,
		TwitterHandle:                new.TwitterHandle,
		ScopeNote:                    new.ScopeNote,
		ShortLabel:                   new.ShortLabel,
		BroaderUUIDs:                 new.BroaderUUIDs,
		RelatedUUIDs:                 new.RelatedUUIDs,
		SupersededByUUIDs:            new.SupersededByUUIDs,
		ImpliedByUUIDs:               new.ImpliedByUUIDs,
		HasFocusUUIDs:                new.HasFocusUUIDs,
		OrganisationUUID:             new.OrganisationUUID,
		PersonUUID:                   new.PersonUUID,
		Hash:                         new.Hash,
		MembershipRoles:              new.MembershipRoles,
		InceptionDate:                new.InceptionDate,
		TerminationDate:              new.TerminationDate,
		InceptionDateEpoch:           new.InceptionDateEpoch,
		TerminationDateEpoch:         new.TerminationDateEpoch,
		FigiCode:                     new.FigiCode,
		IssuedBy:                     new.IssuedBy,
		ProperName:                   new.ProperName,
		ShortName:                    new.ShortName,
		TradeNames:                   new.TradeNames,
		FormerNames:                  new.FormerNames,
		CountryCode:                  new.CountryCode,
		CountryOfRisk:                new.CountryOfRisk,
		CountryOfIncorporation:       new.CountryOfIncorporation,
		CountryOfOperations:          new.CountryOfOperations,
		CountryOfRiskUUID:            new.CountryOfRiskUUID,
		CountryOfIncorporationUUID:   new.CountryOfIncorporationUUID,
		CountryOfOperationsUUID:      new.CountryOfOperationsUUID,
		PostalCode:                   new.PostalCode,
		YearFounded:                  new.YearFounded,
		LeiCode:                      new.LeiCode,
		ParentOrganisation:           new.ParentOrganisation,
		NAICSIndustryClassifications: new.NAICSIndustryClassifications,
		IsDeprecated:                 new.IsDeprecated,
		ISO31661:                     new.ISO31661,
		Salutation:                   new.Salutation,
		BirthYear:                    new.BirthYear,
		IndustryIdentifier:           new.IndustryIdentifier,
	}
}
